name: Setup NetBeans
description: Download and extract a NetBeans ZIP distribution
author: Carlos Machado
inputs:
  version:
    description: NetBeans version
    required: true
runs:
  using: composite
  steps:
    - name: Setup environment
      id: nbenv
      run: |
        echo "NETBEANS_VERSION=${{ inputs.version }}" >> "${GITHUB_OUTPUT}"
    - name: Cache NetBeans distribution
      uses: actions/cache@v4
      id: cache-netbeans
      with:
        path: ${{ github.workspace }}/netbeans
        key: ${{ runner.os }}-netbeans-${{ steps.nbenv.outputs.NETBEANS_VERSION }}
        restore-keys: |
          ${{ runner.os }}-netbeans-${{ env.NETBEANS_VERSION }}
          ${{ runner.os }}-netbeans-
          ${{ runner.os }}-
    
    - name: Download NetBeans ${{ steps.nbenv.outputs.NETBEANS_VERSION }} ZIP distribution
      shell: bash
      run: wget -q https://archive.apache.org/dist/netbeans/netbeans/${{ steps.nbenv.outputs.NETBEANS_VERSION }}/netbeans-${{ steps.nbenv.outputs.NETBEANS_VERSION }}-bin.zip
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
    
    - name: Download NetBeans ${{ steps.nbenv.outputs.NETBEANS_VERSION }} ZIP checksum archive
      shell: bash
      run: wget -q https://archive.apache.org/dist/netbeans/netbeans/${{ steps.nbenv.outputs.NETBEANS_VERSION }}/netbeans-${{ steps.nbenv.outputs.NETBEANS_VERSION }}-bin.zip.sha512
      if: steps.cache-netbeans.outputs.cache-hit != 'true'

    - name: Verify NetBeans ${{ steps.nbenv.outputs.NETBEANS_VERSION }} ZIP distribution
      shell: bash
      run: sha512sum -c netbeans-${{ steps.nbenv.outputs.NETBEANS_VERSION }}-bin.zip.sha512
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
      
    - name: Unzip Netbeans ${{ steps.nbenv.outputs.NETBEANS_VERSION }} ZIP distribution
      shell: bash
      run: unzip -q netbeans-${{ steps.nbenv.outputs.NETBEANS_VERSION }}-bin.zip
      if: steps.cache-netbeans.outputs.cache-hit != 'true'
